lazy_builder.py: handle empty input file nicer
Before the change empty input file caused failure
in bug validation (quite deep in the stack)::

```
Traceback (most recent call last):
  File "./lazy_builder.py", line 165, in <module>
    main()
  File "./lazy_builder.py", line 159, in main
    task = Task(task_spec)
  File "./lazy_builder.py", line 61, in __init__
    self.bug_number = Spec.get_bug(bug_string)
  File "./lazy_builder.py", line 35, in get_bug
    return int(m.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

Skip empty specs early.

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>